version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: betterads_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: betterads_db
      POSTGRES_USER: betterads_user
      POSTGRES_PASSWORD: betterads_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - betterads_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U betterads_user -d betterads_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: betterads_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@betterads.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - betterads_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betterads_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://betterads_user:betterads_password@postgres:5432/betterads_db?schema=public
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - betterads_network

volumes:
  postgres_data:

networks:
  betterads_network:
    driver: bridge